<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Contact Settings - Niaz Law P.C.</title><link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <style>
        *{box-sizing:border-box}.cs-shell{min-height:100vh;display:grid;grid-template-columns:250px 1fr;background:#f6f4ef}.cs-side{min-height:100vh;padding:25px 14px;background:linear-gradient(160deg,#15191a,#050606);color:#fff}.cs-logo{display:block;margin:0 11px 29px;padding-bottom:23px;border-bottom:1px solid #333}.cs-logo img{width:114px}.cs-label{margin:0 12px 11px;color:#c9bd9f;font:700 9px Arial;letter-spacing:.24em}.cs-nav a{display:flex;align-items:center;gap:13px;padding:12px;margin:2px 0;border-left:2px solid transparent;border-radius:6px;color:#f6f4ef;font:14px Georgia;text-decoration:none}.cs-nav a.active,.cs-nav a:hover{border-left-color:#c29c53;background:linear-gradient(90deg,rgba(175,137,67,.32),rgba(175,137,67,.08))}.cs-nav svg{width:18px;height:18px;flex:0 0 18px}.cs-main{padding:38px clamp(24px,5vw,76px)}.cs-content{max-width:900px;margin:auto}.cs-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:28px}.cs-top p{margin:0 0 8px;color:#9a8052;font:700 10px Arial;letter-spacing:.18em}.cs-top h1{margin:0;font:700 38px Georgia}.cs-back{padding:12px 16px;border:1px solid #222;background:#fff;color:#111;font:700 13px Arial;text-decoration:none}.cs-card{padding:28px;border:1px solid #dfdad1;border-radius:9px;background:#fff}.cs-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.cs-field{display:flex;flex-direction:column;gap:8px}.cs-field.full{grid-column:1/-1}.cs-field label{font:700 14px Arial}.cs-field input,.cs-field textarea{width:100%;padding:14px;border:1px solid #cfc9be;border-radius:4px;font:15px Arial}.cs-field textarea{min-height:105px;resize:vertical}.cs-save{margin-top:25px;padding:15px 23px;border:0;background:#171717;color:#fff;font:700 14px Arial;cursor:pointer}.cs-success{padding:14px;background:#f3ede0;color:#51452f;border-left:3px solid #9b7a40}@media(max-width:850px){.cs-shell{grid-template-columns:1fr}.cs-side{min-height:auto}.cs-nav{display:flex;overflow:auto}.cs-nav a{white-space:nowrap}.cs-main{padding:28px 18px}}@media(max-width:600px){.cs-grid{grid-template-columns:1fr}.cs-field.full{grid-column:auto}.cs-top{align-items:flex-start;gap:18px;flex-direction:column}.cs-top h1{font-size:30px}}
    </style>
</head>
<body><div class="cs-shell"><aside class="cs-side">
    <a class="cs-logo" href="{{ route('admin.dashboard') }}"><img src="{{ asset('images/header-logo.png') }}" alt="Niaz Law P.C."></a><p class="cs-label">WEBSITE MANAGEMENT</p>
    <nav class="cs-nav"><a href="{{ route('admin.home-settings.edit') }}"><x-admin-icon name="home"/>Home Page Setting</a><a href="{{ route('admin.attorneys.create') }}"><x-admin-icon name="user"/>Add Attorney</a><a href="#"><x-admin-icon name="users"/>Attorney Page</a><a href="{{ route('admin.capabilities.index') }}"><x-admin-icon name="chart"/>Capabilities</a><a class="active" href="{{ route('admin.contact-settings.edit') }}"><x-admin-icon name="mail"/>Contact Us</a><a href="#"><x-admin-icon name="file"/>Case Study</a><a href="#"><x-admin-icon name="edit"/>Blog Page</a><a href="#"><x-admin-icon name="bulb"/>Insight Page</a></nav>
</aside><main class="cs-main"><div class="cs-content"><header class="cs-top"><div><p>WEBSITE MANAGEMENT</p><h1>Contact Information</h1></div><a class="cs-back" href="{{ route('admin.dashboard') }}">← Back to dashboard</a></header>
@if(session('success'))<p class="cs-success">{{ session('success') }}</p>@endif
<form class="cs-card" method="post" action="{{ route('admin.contact-settings.update') }}">@csrf @method('PUT')<div class="cs-grid">
<div class="cs-field"><label for="franklin">Franklin Park Office Address</label><textarea id="franklin" name="franklin_address" required>{{ old('franklin_address',$settings->franklin_address) }}</textarea></div>
<div class="cs-field"><label for="naperville">Naperville / Lisle Office Address</label><textarea id="naperville" name="naperville_address" required>{{ old('naperville_address',$settings->naperville_address) }}</textarea></div>
<div class="cs-field"><label for="phone">Phone Number</label><input id="phone" name="phone" value="{{ old('phone',$settings->phone) }}" required></div>
<div class="cs-field"><label for="email">Email Address</label><input id="email" type="email" name="email" value="{{ old('email',$settings->email) }}" required></div>
</div><button class="cs-save" type="submit">Save contact information</button></form>
</div></main></div></body></html>
