<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard - Niaz Law P.C.</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <style>
        :root { --admin-black:#111311; --admin-paper:#f8f6f1; --admin-gold:#b89a61; --admin-line:#e6e1d8; --admin-muted:#777771; }
        .admin-dashboard { min-height:100vh; background:var(--admin-paper); color:#20211f; }
        .admin-shell { min-height:100vh; display:grid; grid-template-columns:250px 1fr; }
        .admin-sidebar { display:flex; flex-direction:column; padding:31px 18px 20px; background:linear-gradient(160deg,#151715,#090a09); color:#fff; }
        .admin-logo { display:block; padding:0 17px 31px; border-bottom:1px solid rgba(255,255,255,.12); }.admin-logo img { width:137px; }
        .admin-label { margin:25px 10px 12px; color:#b2ad9f; font-size:9px; font-weight:700; letter-spacing:.24em; text-transform:uppercase; }
        .admin-nav { display:grid; gap:5px; }.admin-nav a { display:flex; align-items:center; gap:14px; min-height:44px; padding:0 12px; border-radius:5px; color:#f0efe9; font-size:14px; }.admin-nav a.active { background:linear-gradient(90deg,rgba(184,154,97,.45),rgba(184,154,97,.17)); color:#fff; }.admin-nav a:hover { background:rgba(255,255,255,.08); }
        .admin-nav__icon { width:16px; height:16px; flex:0 0 16px; color:#fff; }.admin-ui-icon { width:18px; height:18px; }.admin-side-footer { margin-top:auto; padding:21px 11px 0; border-top:1px solid rgba(255,255,255,.13); }.admin-side-footer a,.admin-side-footer button { display:flex; align-items:center; gap:8px; margin:0 0 14px; padding:0; border:0; background:none; color:#e6e3dc; font:13px var(--font-body); cursor:pointer; }
        .admin-main { padding:23px 38px 16px; overflow:hidden; }.admin-top { display:flex; align-items:flex-start; justify-content:space-between; gap:25px; }.admin-overline { margin:0 0 7px; color:#9a8052; font-size:10px; font-weight:700; letter-spacing:.22em; text-transform:uppercase; }.admin-top h1 { margin:0; font-size:30px; line-height:1.1; }.admin-subtitle { margin:7px 0 0; color:#77746e; font-size:14px; }
        .admin-top-actions { display:flex; align-items:center; gap:20px; }.admin-search { display:flex; align-items:center; width:200px; height:36px; padding:0 12px; border:1px solid var(--admin-line); border-radius:5px; background:#fff; color:#9b9790; font-size:11px; }.admin-search span { margin-right:8px; font-size:16px; }.admin-bell { position:relative; font-size:19px; }.admin-bell::after { content:''; position:absolute; top:0; right:-4px; width:5px; height:5px; border-radius:50%; background:#caa55e; }.admin-avatar { width:31px; height:31px; display:grid; place-items:center; border-radius:50%; background:#111; color:#fff; font-size:12px; font-weight:700; }
        .admin-motto { margin:21px 0 19px auto; color:#866f49; font-size:8px; font-weight:700; letter-spacing:.32em; text-align:right; text-transform:uppercase; }.admin-motto::before { content:''; display:inline-block; width:44px; margin:0 13px 3px 0; border-top:1px solid #c1a06a; }
        .admin-stats { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:14px; }.admin-stat { min-height:107px; padding:19px; display:grid; grid-template-columns:43px 1fr 13px; align-items:start; border:1px solid #ece8e0; border-radius:5px; background:#fff; box-shadow:0 5px 14px rgba(0,0,0,.035); }.admin-stat__icon { width:35px; height:35px; display:grid; place-items:center; border-radius:50%; background:#f5efdf; color:#765d2e; font-size:19px; }.admin-stat p { margin:0; font:13px var(--font-heading); }.admin-stat strong { display:block; margin-top:4px; font:28px var(--font-heading); }.admin-stat small { color:#85817b; font-size:10px; }.admin-stat__arrow { color:#777; font-size:17px; text-align:right; }
        .admin-panels { display:grid; grid-template-columns:1.08fr .92fr; gap:14px; margin-top:16px; }.admin-panel { padding:19px; border:1px solid #ece8e0; border-radius:5px; background:#fff; box-shadow:0 5px 14px rgba(0,0,0,.035); }.admin-panel h2 { margin:0; font-size:20px; }.admin-panel__intro { margin:3px 0 13px; color:#8b8781; font-size:11px; }
        .admin-task { display:grid; grid-template-columns:39px 1fr 18px; gap:12px; align-items:center; min-height:53px; margin-top:8px; padding:7px 10px; border:1px solid #ebe7df; border-radius:5px; }.admin-task__icon { width:32px; height:32px; display:grid; place-items:center; border-radius:5px; background:#f5efdf; color:#745f39; font-size:17px; }.admin-task strong { display:block; font-size:12px; }.admin-task small { display:block; margin-top:3px; color:#85817b; font-size:10px; }.admin-task__arrow { color:#555; font-size:18px; }
        .admin-overview { position:relative; min-height:202px; overflow:hidden; padding:21px; border-left:3px solid #b58d43; background:linear-gradient(90deg,#fbfaf6 20%,rgba(251,250,246,.52)),url('{{ asset('images/attorney-hero.jpg') }}') right center/cover; }.admin-overview h3 { margin:35px 0 12px; font-size:20px; }.admin-overview p { max-width:255px; margin:0; color:#65615b; font-size:11px; line-height:1.6; }.admin-quote { margin:17px 0 0; color:#726d66; font:italic 14px var(--font-heading); }.admin-quote::before { content:'“'; color:#d5c6a9; font-size:33px; vertical-align:middle; }
        .admin-activity { display:flex; align-items:center; justify-content:space-between; min-height:60px; margin-top:14px; padding:12px 16px; border:1px solid #ece8e0; border-radius:5px; background:#fff; }.admin-activity h2 { margin:0; font-size:17px; }.admin-activity p { margin:3px 0 0; color:#89847e; font-size:10px; }.admin-activity a { padding:9px 14px; border-radius:4px; background:#f5efdf; color:#5e5037; font-size:11px; }
        .admin-bottom { display:flex; justify-content:space-between; margin-top:17px; color:#8d8880; font-size:8px; letter-spacing:.09em; }.admin-bottom span { margin-right:12px; }
        @media (max-width:1000px) { .admin-shell{grid-template-columns:1fr}.admin-sidebar{padding:18px}.admin-logo{padding-bottom:18px}.admin-nav{grid-template-columns:repeat(2,1fr)}.admin-side-footer{display:none}.admin-main{padding:25px}.admin-stats{grid-template-columns:repeat(2,1fr)}.admin-panels{grid-template-columns:1fr}.admin-bottom{display:none} }
        @media (max-width:600px) { .admin-main{padding:20px 14px}.admin-top{display:block}.admin-top-actions{margin-top:20px}.admin-search{width:100%}.admin-motto{display:none}.admin-nav{grid-template-columns:1fr}.admin-stats{grid-template-columns:1fr}.admin-stat{min-height:90px}.admin-sidebar{padding:15px}.admin-sidebar__logo{padding-left:8px}.admin-panels{margin-top:12px} }
    </style>
</head>
<body class="admin-dashboard">
    <div class="admin-shell">
        <aside class="admin-sidebar">
            <a class="admin-logo" href="/"><img src="{{ asset('images/header-logo.png') }}" alt="Niaz Law P.C."></a>
            <p class="admin-label">Website Management</p>
            <nav class="admin-nav">
                <a class="active" href="{{ route('admin.home-settings.edit') }}"><x-admin-icon name="home" class="admin-nav__icon"/>Home Page Setting</a>
                <a href="#"><x-admin-icon name="user" class="admin-nav__icon"/>Add Attorney</a><a href="#"><x-admin-icon name="users" class="admin-nav__icon"/>Attorney Page</a><a href="#"><x-admin-icon name="chart" class="admin-nav__icon"/>Capabilities</a><a href="{{ route('admin.contact-settings.edit') }}"><x-admin-icon name="mail" class="admin-nav__icon"/>Contact Us</a><a href="#"><x-admin-icon name="file" class="admin-nav__icon"/>Case Study</a><a href="#"><x-admin-icon name="edit" class="admin-nav__icon"/>Blog Page</a><a href="#"><x-admin-icon name="bulb" class="admin-nav__icon"/>Insight Page</a>
            </nav>
            <div class="admin-side-footer"><a href="/" target="_blank"><x-admin-icon name="external"/>View website</a><form method="post" action="{{ route('admin.logout') }}">@csrf<button type="submit"><x-admin-icon name="logout"/>Sign out</button></form></div>
        </aside>
        <main class="admin-main">
            <header class="admin-top"><div><p class="admin-overline">Administration</p><h1>Welcome back, Admin</h1><p class="admin-subtitle">Manage your website content, track insights, and keep Niaz Law P.C. up to date.</p></div><div class="admin-top-actions"><div class="admin-search"><x-admin-icon name="search"/>Search pages, content...</div><span class="admin-bell"><x-admin-icon name="bell"/></span><span class="admin-avatar">A</span></div></header>
            <p class="admin-motto">Law for a better tomorrow</p>
            <section class="admin-stats"><article class="admin-stat"><span class="admin-stat__icon"><x-admin-icon name="users"/></span><div><p>Attorneys</p><strong>0</strong><small>Total attorneys on your site</small></div><span class="admin-stat__arrow">→</span></article><article class="admin-stat"><span class="admin-stat__icon"><x-admin-icon name="file"/></span><div><p>Case Studies</p><strong>7</strong><small>Published case studies</small></div><span class="admin-stat__arrow">→</span></article><article class="admin-stat"><span class="admin-stat__icon"><x-admin-icon name="edit"/></span><div><p>Blog Articles</p><strong>8</strong><small>Published blog articles</small></div><span class="admin-stat__arrow">→</span></article><article class="admin-stat"><span class="admin-stat__icon"><x-admin-icon name="bulb"/></span><div><p>Insights</p><strong>10</strong><small>Published insights</small></div><span class="admin-stat__arrow">→</span></article></section>
            <section class="admin-panels"><article class="admin-panel"><h2>Quick access</h2><p class="admin-panel__intro">Common tasks to manage your website content.</p><a href="{{ route('admin.home-settings.edit') }}" class="admin-task"><span class="admin-task__icon"><x-admin-icon name="file"/></span><div><strong>Update home page content</strong><small>Edit your home page section, and key content.</small></div><span class="admin-task__arrow">→</span></a><div class="admin-task"><span class="admin-task__icon"><x-admin-icon name="user"/></span><div><strong>Add an attorney</strong><small>Create a new attorney profile.</small></div><span class="admin-task__arrow">→</span></div><div class="admin-task"><span class="admin-task__icon"><x-admin-icon name="mail"/></span><div><strong>Review contact details</strong><small>Update the firm’s contact information.</small></div><span class="admin-task__arrow">→</span></div><div class="admin-task"><span class="admin-task__icon"><x-admin-icon name="bulb"/></span><div><strong>Publish an insight</strong><small>Share your latest thought leadership content.</small></div><span class="admin-task__arrow">→</span></div></article><article class="admin-panel"><h2>Content overview</h2><p class="admin-panel__intro">Manage your website's public content.</p><div class="admin-overview"><h3>Keep your content current</h3><p>Use the sidebar to manage each public page. Your changes will shape the Niaz Law P.C. website experience and help tell your firm's story.</p></div><p class="admin-quote">Good law is not a privilege, it is a foundation for stronger communities.</p></article></section>
            <section class="admin-activity"><div><h2>◷ &nbsp; Recent activity</h2><p>Your latest updates and changes.</p></div><a href="#">View all activity &nbsp; →</a></section><footer class="admin-bottom"><div><span>NIAZ LAW P.C.</span><span>Administration Panel</span></div><div><span>EXCELLENCE</span><span>INTEGRITY</span><span>RESULTS</span></div></footer>
        </main>
    </div>
</body>
</html>
