<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Add Attorney - Niaz Law P.C.</title><link rel="stylesheet" href="{{ asset('css/app.css') }}">
<style>
*{box-sizing:border-box}.at-shell{min-height:100vh;display:grid;grid-template-columns:250px 1fr;background:#f6f4ef}.at-side{padding:25px 14px;background:linear-gradient(160deg,#15191a,#050606);color:#fff}.at-logo{display:block;margin:0 11px 29px;padding-bottom:23px;border-bottom:1px solid #333}.at-logo img{width:114px}.at-label{margin:0 12px 11px;color:#c9bd9f;font:700 9px Arial;letter-spacing:.24em}.at-nav a{display:flex;align-items:center;gap:13px;padding:12px;margin:2px 0;border-left:2px solid transparent;border-radius:6px;color:#f6f4ef;font:14px Georgia;text-decoration:none}.at-nav a.active,.at-nav a:hover{border-left-color:#c29c53;background:linear-gradient(90deg,rgba(175,137,67,.32),rgba(175,137,67,.08))}.at-nav svg{width:18px;height:18px}.at-main{padding:38px clamp(24px,5vw,76px)}.at-content{max-width:950px;margin:auto}.at-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:26px}.at-top p{margin:0 0 8px;color:#9a8052;font:700 10px Arial;letter-spacing:.18em}.at-top h1{margin:0;font:700 38px Georgia}.at-back{padding:12px 16px;border:1px solid #222;background:#fff;color:#111;font:700 13px Arial;text-decoration:none}.at-card{padding:28px;border:1px solid #dfdad1;border-radius:9px;background:#fff}.at-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.at-field{display:flex;flex-direction:column;gap:8px}.at-field.full{grid-column:1/-1}.at-field label{font:700 14px Arial}.at-field input,.at-field select{width:100%;height:50px;padding:12px 14px;border:1px solid #cfc9be;border-radius:4px;background:#fff;font:15px Arial}.at-hint{margin:0;color:#777;font-size:12px}.at-save{margin-top:25px;padding:15px 23px;border:0;background:#171717;color:#fff;font:700 14px Arial;cursor:pointer}.at-success{padding:14px;background:#f3ede0;color:#51452f;border-left:3px solid #9b7a40}.at-error{margin:0;color:#a01f1f;font-size:12px}.at-list{margin-top:34px}.at-list h2{margin:0 0 16px;font:700 28px Georgia}.at-list-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.at-person{display:flex;gap:15px;padding:14px;border:1px solid #dfdad1;background:#fff}.at-person img{width:86px;height:98px;object-fit:cover}.at-person h3{margin:2px 0 6px;font:700 18px Georgia}.at-person p{margin:3px 0;font:13px Arial}@media(max-width:850px){.at-shell{grid-template-columns:1fr}.at-side{min-height:auto;padding:16px}.at-nav{display:flex;overflow:auto}.at-nav a{white-space:nowrap}.at-main{padding:28px 18px}}@media(max-width:600px){.at-grid,.at-list-grid{grid-template-columns:1fr}.at-field.full{grid-column:auto}.at-top{align-items:flex-start;gap:18px;flex-direction:column}.at-top h1{font-size:30px}}
 .at-checks{display:grid;gap:7px;padding:11px;border:1px solid #cfc9be;border-radius:4px;background:#fff}.at-checks label{display:flex;align-items:center;gap:9px;font:14px Arial;cursor:pointer}.at-checks input{width:17px!important;height:17px!important;padding:0!important;accent-color:#171717}.at-field small{color:#777;font-weight:400}.at-edit{display:inline-block;margin-top:9px;padding:7px 10px;background:#171717;color:#fff;font:700 12px Arial;text-decoration:none}.at-delete-form{display:inline-block;margin-left:7px}.at-delete{padding:7px 10px;border:1px solid #a8342d;background:#fff;color:#9c2f29;font:700 12px Arial;cursor:pointer}.at-field textarea{width:100%;min-height:110px;padding:12px 14px;border:1px solid #cfc9be;border-radius:4px;background:#fff;font:15px Arial;resize:vertical}</style></head>
<body><div class="at-shell"><aside class="at-side"><a class="at-logo" href="{{ route('admin.dashboard') }}"><img src="{{ asset('images/header-logo.png') }}" alt="Niaz Law P.C."></a><p class="at-label">WEBSITE MANAGEMENT</p><nav class="at-nav"><a href="{{ route('admin.home-settings.edit') }}"><x-admin-icon name="home"/>Home Page Setting</a><a class="active" href="{{ route('admin.attorneys.create') }}"><x-admin-icon name="user"/>Add Attorney</a><a href="{{ route('admin.attorneys.details') }}"><x-admin-icon name="users"/>Attorney Detail Page</a><a href="{{ route('admin.capabilities.index') }}"><x-admin-icon name="chart"/>Capabilities</a><a href="{{ route('admin.capabilities.pages') }}"><x-admin-icon name="file"/>Capability Pages</a><a href="{{ route('admin.contact-settings.edit') }}"><x-admin-icon name="mail"/>Contact Us</a><p style="margin:22px 12px 8px;color:#c9bd9f;font:700 9px Arial;letter-spacing:.24em">INSIGHTS &amp; RESOURCES</p><div style="margin-left:8px"><a href="{{ route('admin.blog.index') }}"><x-admin-icon name="edit"/>Blog</a><a href="{{ url('/admin/blog?type=case_study') }}"><x-admin-icon name="file"/>Case Study</a><a href="{{ url('/admin/blog?type=insight') }}"><x-admin-icon name="bulb"/>Insight</a></div></nav></aside>
<main class="at-main"><div class="at-content"><header class="at-top"><div><p>WEBSITE MANAGEMENT</p><h1>Add Attorney</h1></div><a class="at-back" href="{{ route('admin.dashboard') }}">← Back to dashboard</a></header>@if(session('success'))<p class="at-success">{{ session('success') }}</p>@endif
<form class="at-card" method="post" action="{{ route('admin.attorneys.store') }}" enctype="multipart/form-data">@csrf<div class="at-grid">
<div class="at-field full"><label for="photo">Attorney Photo</label><input id="photo" type="file" name="photo" accept=".jpg,.jpeg,.png,.webp,image/*"><p class="at-hint">JPG, PNG or WEBP image, maximum 5 MB.</p>@error('photo')<p class="at-error">{{ $message }}</p>@enderror</div>
<div class="at-field full"><label for="name">Full Name</label><input id="name" name="name" value="{{ old('name') }}" placeholder="Attorney full name" required>@error('name')<p class="at-error">{{ $message }}</p>@enderror</div>
@php($practiceOptions=['Commercial Transactions','Infrastructure & Projects','Procurement & Contracting','Aviation','Commercial Risk','International Business','Corporate Transactions & Governance','Commercial Operations & Strategic Sourcing','Infrastructure & Construction','Aviation & Transportation','Real Estate Transactions'])
@php($industryOptions=['Aviation','Energy & Infrastructure','Technology','Healthcare & Life Sciences','Real Estate & Construction'])
<div class="at-field"><label>Practice <small>(select one or more)</small></label><div class="at-checks" data-custom-checks="practice">@foreach($practiceOptions as $value)<label><input type="checkbox" name="practice[]" value="{{ $value }}" @if(in_array($value, old('practice', []))) checked @endif><span>{{ $value }}</span></label>@endforeach</div><input data-custom-input="practice" name="practice_custom" value="{{ old('practice_custom') }}" placeholder="Other practice (optional)">@error('practice')<p class="at-error">{{ $message }}</p>@enderror</div>
<div class="at-field"><label>Industry <small>(select one or more)</small></label><div class="at-checks" data-custom-checks="industry">@foreach($industryOptions as $value)<label><input type="checkbox" name="industry[]" value="{{ $value }}" @if(in_array($value, old('industry', []))) checked @endif><span>{{ $value }}</span></label>@endforeach</div><input data-custom-input="industry" name="industry_custom" value="{{ old('industry_custom') }}" placeholder="Other industry (optional)">@error('industry')<p class="at-error">{{ $message }}</p>@enderror</div>
<div class="at-field"><label>Assign to capabilities <small>(select one or more)</small></label><div class="at-checks">@foreach($capabilities as $capability)<label><input type="checkbox" name="capabilities[]" value="{{ $capability->id }}" @checked(in_array($capability->id, old('capabilities', [])))><span>{{ $capability->title }}</span></label>@endforeach</div></div>
<div class="at-field"><label>Location <small>(select one or more)</small></label><div class="at-checks">@foreach(['Franklin Park','Naperville / Lisle'] as $value)<label><input type="checkbox" name="location[]" value="{{ $value }}" @checked(in_array($value, old('location', [])))><span>{{ $value }}</span></label>@endforeach</div>@error('location')<p class="at-error">{{ $message }}</p>@enderror</div>
<div class="at-field"><label for="title">Title</label><select id="title" name="title" required><option value="">Select title</option>@foreach(['Partner','Senior of Counsel','Senior Counsel','Counsel','Associate Attorney'] as $value)<option value="{{ $value }}" @if(old('title') === $value) selected @endif>{{ $value }}</option>@endforeach</select></div>
</div><button class="at-save" type="submit">Save attorney</button></form>
<script>
document.querySelectorAll('[data-custom-input]').forEach(function(input){
  var type=input.dataset.customInput, list=document.querySelector('[data-custom-checks="'+type+'"]');
  function add(){var value=input.value.trim(); if(!value)return; var exists=[...list.querySelectorAll('input')].some(function(item){return item.value.toLowerCase()===value.toLowerCase()}); if(!exists){var label=document.createElement('label'); label.innerHTML='<input type="checkbox" name="'+type+'[]" value=""> <span></span>'; label.querySelector('input').value=value; label.querySelector('input').checked=true; label.querySelector('span').textContent=value; list.appendChild(label)} input.value='';}
  input.addEventListener('change',add); input.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();add()}}); input.form.addEventListener('submit',add);
});
</script>
@if($attorneys->isNotEmpty())<section class="at-list"><h2>Added Attorneys</h2><div class="at-list-grid">@foreach($attorneys as $attorney)<article class="at-person"><img src="{{ asset('images/' . ($attorney->photo ?: 'lawyer_profile.jpg')) }}" alt="{{ $attorney->name }}"><div><h3>{{ $attorney->name }}</h3><p>{{ $attorney->title }} · {{ $attorney->location }}</p><p>{{ $attorney->practice }}</p><p>{{ $attorney->email }}</p><p>{{ $attorney->phone }}</p><a class="at-edit" href="{{ route('admin.attorneys.edit',$attorney) }}">Edit attorney</a><form class="at-delete-form" method="post" action="{{ route('admin.attorneys.destroy',$attorney) }}" onsubmit="return confirm('Delete {{ $attorney->name }}? This cannot be undone.')">@csrf @method('DELETE')<button class="at-delete" type="submit">Delete attorney</button></form></div></article>@endforeach</div></section>@endif
</div></main></div></body></html>
