<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Edit Attorney</title><link rel="stylesheet" href="{{ asset('css/app.css') }}">
<style>
*{box-sizing:border-box}.edit-page{min-height:100vh;padding:42px 20px;background:#f6f4ef}.edit-wrap{max-width:850px;margin:auto}.edit-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.edit-top h1{margin:0;font:700 38px Georgia}.edit-back{padding:12px 16px;border:1px solid #222;background:#fff;color:#111;text-decoration:none;font:700 13px Arial}.edit-card{padding:28px;background:#fff;border:1px solid #dfdad1;border-radius:9px}.edit-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.edit-field{display:flex;flex-direction:column;gap:8px}.edit-field.full{grid-column:1/-1}.edit-field label{font:700 14px Arial}.edit-field input,.edit-field select{height:48px;padding:12px;border:1px solid #cfc9be;border-radius:4px;font:15px Arial}.edit-field textarea{width:100%;min-height:116px;padding:14px;border:1px solid #cfc9be;border-radius:4px;background:#fff;color:#171717;font:15px/1.55 Arial;resize:vertical;outline:none}.edit-field textarea:focus,.edit-field input:focus,.edit-field select:focus{border-color:#171717;box-shadow:0 0 0 2px rgba(23,23,23,.08)}.edit-checks{display:grid;gap:7px;padding:11px;border:1px solid #cfc9be;border-radius:4px}.edit-checks label{display:flex;gap:8px;align-items:center;font:14px Arial}.edit-checks input{width:17px;height:17px;accent-color:#171717}.edit-custom-entry{display:flex;gap:8px;align-items:center}.edit-custom-entry input{min-width:0;flex:1}.edit-custom-add{height:48px;padding:0 18px;border:0;border-radius:4px;background:#b88d43;color:#fff;font:700 14px Arial;white-space:nowrap;cursor:pointer}.edit-custom-add:hover{background:#9d7435}.edit-photo{width:95px;height:105px;object-fit:cover;margin-bottom:8px}.edit-save{margin-top:25px;padding:15px 23px;border:0;background:#171717;color:#fff;font:700 14px Arial;cursor:pointer}@media(max-width:600px){.edit-grid{grid-template-columns:1fr}.edit-field.full{grid-column:auto}.edit-top{align-items:flex-start;gap:15px;flex-direction:column}}@media(max-width:480px){.edit-custom-entry{align-items:stretch;flex-direction:column}.edit-custom-add{width:100%}}
</style></head><body><main class="edit-page"><div class="edit-wrap"><header class="edit-top"><h1>Edit Attorney</h1><a class="edit-back" href="{{ route('admin.attorneys.create') }}">← Back to attorneys</a></header>
@php($practices=explode(', ', $attorney->practice)) @php($industries=explode(', ', $attorney->industry)) @php($locations=explode(', ', $attorney->location))
@php($practiceOptions=['Commercial Transactions','Infrastructure & Projects','Procurement & Contracting','Aviation','Commercial Risk','International Business','Corporate Transactions & Governance','Commercial Operations & Strategic Sourcing','Infrastructure & Construction','Aviation & Transportation','Real Estate Transactions'])
@php($industryOptions=['Aviation','Energy & Infrastructure','Technology','Healthcare & Life Sciences','Real Estate & Construction'])
@php($practiceOptions=array_values(array_unique(array_merge($practiceOptions, $practices))))
@php($industryOptions=array_values(array_unique(array_merge($industryOptions, $industries))))
<form class="edit-card" method="post" action="{{ route('admin.attorneys.update',$attorney) }}" enctype="multipart/form-data">@csrf @method('PUT')<div class="edit-grid">
<div class="edit-field full"><label>Photo</label><img class="edit-photo" src="{{ asset('images/' . ($attorney->photo ?: 'lawyer_profile.jpg')) }}" alt="{{ $attorney->name }}"><input type="file" name="photo" accept=".jpg,.jpeg,.png,.webp,image/*"></div>
<div class="edit-field full"><label>Name</label><input name="name" value="{{ old('name',$attorney->name) }}" required></div>
<div class="edit-field full"><label for="slug">Attorney Detail Page Slug</label><input id="slug" name="slug" value="{{ old('slug',$attorney->slug) }}" pattern="[A-Za-z0-9-]+" required aria-describedby="slug-help"><small id="slug-help">Public URL: /attorneys/{{ old('slug',$attorney->slug) }}</small>@error('slug')<small class="edit-error">{{ $message }}</small>@enderror</div>
<div class="edit-field"><label>Practice</label><div class="edit-checks" data-custom-checks="practice">@foreach($practiceOptions as $v)<label><input type="checkbox" name="practice[]" value="{{ $v }}" @if(in_array($v, old('practice', $practices))) checked @endif>{{ $v }}</label>@endforeach</div><div class="edit-custom-entry"><input data-custom-input="practice" name="practice_custom" placeholder="Add another practice"><button class="edit-custom-add" type="button" data-custom-add="practice">Add</button></div></div>
<div class="edit-field"><label>Industry</label><div class="edit-checks" data-custom-checks="industry">@foreach($industryOptions as $v)<label><input type="checkbox" name="industry[]" value="{{ $v }}" @if(in_array($v, old('industry', $industries))) checked @endif>{{ $v }}</label>@endforeach</div><div class="edit-custom-entry"><input data-custom-input="industry" name="industry_custom" placeholder="Add another industry"><button class="edit-custom-add" type="button" data-custom-add="industry">Add</button></div></div>
<div class="edit-field"><label>Assign to capabilities</label><div class="edit-checks">@foreach($capabilities as $capability)<label><input type="checkbox" name="capabilities[]" value="{{ $capability->id }}" @checked(in_array($capability->id, old('capabilities', $attorney->capabilities->pluck('id')->all())))>{{ $capability->title }}</label>@endforeach</div></div>
<div class="edit-field"><label>Location</label><div class="edit-checks">@foreach(['Franklin Park','Naperville / Lisle'] as $v)<label><input type="checkbox" name="location[]" value="{{ $v }}" @if(in_array($v, old('location', $locations))) checked @endif>{{ $v }}</label>@endforeach</div></div>
<div class="edit-field"><label>Title</label><select name="title" required>@foreach(['Partner','Senior of Counsel','Senior Counsel','Counsel','Associate Attorney'] as $v)<option value="{{ $v }}" @if(old('title', $attorney->title) === $v) selected @endif>{{ $v }}</option>@endforeach</select></div>
<div class="edit-field"><label>Email</label><input type="email" name="email" value="{{ old('email',$attorney->email) }}" required></div><div class="edit-field"><label>Phone</label><input name="phone" value="{{ old('phone',$attorney->phone) }}" required></div>
<div class="edit-field full"><label>Overview</label><textarea name="overview">{{ old('overview',$attorney->overview) }}</textarea></div><div class="edit-field full"><label>Experience</label><textarea name="experience">{{ old('experience',$attorney->experience) }}</textarea></div><div class="edit-field full"><label>Experience Points <small>(one point per line)</small></label><textarea name="experience_points">{{ old('experience_points',$attorney->experience_points) }}</textarea></div><div class="edit-field"><label>Education <small>(one item per line)</small></label><textarea name="education">{{ old('education',$attorney->education) }}</textarea></div><div class="edit-field"><label>Admissions <small>(one item per line)</small></label><textarea name="admissions">{{ old('admissions',$attorney->admissions) }}</textarea></div>
</div><div class="edit-field full">
    <h2>SEO & Search Visibility</h2>
</div>
<div class="edit-field">
    <label>Meta Title</label>
    <input name="meta_title" value="{{ old('meta_title', $ITEM->meta_title ?? '') }}">
</div>
<div class="edit-field">
    <label>Robots</label>
    <select name="robots">
        <option {{ old('robots', $ITEM->robots ?? '') === 'index, follow' ? 'selected' : '' }}>index, follow</option>
        <option {{ old('robots', $ITEM->robots ?? '') === 'noindex, nofollow' ? 'selected' : '' }}>noindex, nofollow</option>
        <option {{ old('robots', $ITEM->robots ?? '') === 'index, nofollow' ? 'selected' : '' }}>index, nofollow</option>
    </select>
</div>
<div class="edit-field full">
    <label>Meta Description</label>
    <textarea name="meta_description">{{ old('meta_description', $ITEM->meta_description ?? '') }}</textarea>
</div>
<div class="edit-field full">
    <label>Meta Keywords / Tags</label>
    <input name="meta_keywords" value="{{ old('meta_keywords', $ITEM->meta_keywords ?? '') }}">
</div>
<button class="edit-save" type="submit">Update attorney</button></form><script>
document.querySelectorAll('[data-custom-input]').forEach(function(input){var type=input.dataset.customInput,list=document.querySelector('[data-custom-checks="'+type+'"]');function add(){var value=input.value.trim();if(!value)return;var exists=[...list.querySelectorAll('input')].some(function(item){return item.value.toLowerCase()===value.toLowerCase()});if(!exists){var label=document.createElement('label');label.innerHTML='<input type="checkbox" name="'+type+'[]" value="">'+value;label.querySelector('input').value=value;label.querySelector('input').checked=true;list.appendChild(label)}input.value=''}input.addEventListener('change',add);input.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();add()}});input.form.addEventListener('submit',add)});
</script></div></main><script>document.addEventListener("click",function(e){if(!e.target.matches("[data-custom-add]"))return;var input=document.querySelector("[data-custom-input=\""+e.target.dataset.customAdd+"\"]");if(input){input.dispatchEvent(new Event("change",{bubbles:true}));}});</script></body></html>
