<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Edit Attorney</title><link rel="stylesheet" href="{{ asset('css/app.css') }}">
<style>
*{box-sizing:border-box}.edit-page{min-height:100vh;padding:42px 20px;background:#f6f4ef}.edit-wrap{max-width:850px;margin:auto}.edit-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.edit-top h1{margin:0;font:700 38px Georgia}.edit-back{padding:12px 16px;border:1px solid #222;background:#fff;color:#111;text-decoration:none;font:700 13px Arial}.edit-card{padding:28px;background:#fff;border:1px solid #dfdad1;border-radius:9px}.edit-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.edit-field{display:flex;flex-direction:column;gap:8px}.edit-field.full{grid-column:1/-1}.edit-field label{font:700 14px Arial}.edit-field input,.edit-field select{height:48px;padding:12px;border:1px solid #cfc9be;border-radius:4px;font:15px Arial}.edit-field textarea{width:100%;min-height:116px;padding:14px;border:1px solid #cfc9be;border-radius:4px;background:#fff;color:#171717;font:15px/1.55 Arial;resize:vertical;outline:none}.edit-field textarea:focus,.edit-field input:focus,.edit-field select:focus{border-color:#171717;box-shadow:0 0 0 2px rgba(23,23,23,.08)}.edit-checks{display:grid;gap:7px;padding:11px;border:1px solid #cfc9be;border-radius:4px}.edit-checks label{display:flex;gap:8px;align-items:center;font:14px Arial}.edit-checks input{width:17px;height:17px;accent-color:#171717}.edit-photo{width:95px;height:105px;object-fit:cover;margin-bottom:8px}.edit-save{margin-top:25px;padding:15px 23px;border:0;background:#171717;color:#fff;font:700 14px Arial;cursor:pointer}@media(max-width:600px){.edit-grid{grid-template-columns:1fr}.edit-field.full{grid-column:auto}.edit-top{align-items:flex-start;gap:15px;flex-direction:column}}
</style></head><body><main class="edit-page"><div class="edit-wrap"><header class="edit-top"><h1>Edit Attorney</h1><a class="edit-back" href="{{ route('admin.attorneys.create') }}">← Back to attorneys</a></header>
@php($practices=explode(', ', $attorney->practice)) @php($industries=explode(', ', $attorney->industry)) @php($locations=explode(', ', $attorney->location))
<form class="edit-card" method="post" action="{{ route('admin.attorneys.update',$attorney) }}" enctype="multipart/form-data">@csrf @method('PUT')<div class="edit-grid">
<div class="edit-field full"><label>Photo</label><img class="edit-photo" src="{{ asset('images/' . ($attorney->photo ?: 'lawyer_profile.jpg')) }}" alt="{{ $attorney->name }}"><input type="file" name="photo" accept=".jpg,.jpeg,.png,.webp,image/*"></div>
<div class="edit-field full"><label>Name</label><input name="name" value="{{ old('name',$attorney->name) }}" required></div>
<div class="edit-field"><label>Practice</label><div class="edit-checks">@foreach(['Commercial Transactions','Infrastructure & Projects','Procurement & Contracting','Aviation','Commercial Risk','International Business','Corporate Transactions & Governance','Commercial Operations & Strategic Sourcing','Infrastructure & Construction','Aviation & Transportation','Real Estate Transactions'] as $v)<label><input type="checkbox" name="practice[]" value="{{ $v }}" @if(in_array($v, old('practice', $practices))) checked @endif>{{ $v }}</label>@endforeach</div><input name="practice_custom" placeholder="Other practice (optional)"></div>
<div class="edit-field"><label>Industry</label><div class="edit-checks">@foreach(['Aviation','Energy & Infrastructure','Technology','Healthcare & Life Sciences','Real Estate & Construction'] as $v)<label><input type="checkbox" name="industry[]" value="{{ $v }}" @if(in_array($v, old('industry', $industries))) checked @endif>{{ $v }}</label>@endforeach</div><input name="industry_custom" placeholder="Other industry (optional)"></div>
<div class="edit-field"><label>Location</label><div class="edit-checks">@foreach(['Franklin Park','Naperville / Lisle'] as $v)<label><input type="checkbox" name="location[]" value="{{ $v }}" @if(in_array($v, old('location', $locations))) checked @endif>{{ $v }}</label>@endforeach</div></div>
<div class="edit-field"><label>Title</label><select name="title" required>@foreach(['Partner','Senior of Counsel','Senior Counsel','Counsel','Associate Attorney'] as $v)<option value="{{ $v }}" @if(old('title', $attorney->title) === $v) selected @endif>{{ $v }}</option>@endforeach</select></div>
<div class="edit-field"><label>Email</label><input type="email" name="email" value="{{ old('email',$attorney->email) }}" required></div><div class="edit-field"><label>Phone</label><input name="phone" value="{{ old('phone',$attorney->phone) }}" required></div>
<div class="edit-field full"><label>Overview</label><textarea name="overview">{{ old('overview',$attorney->overview) }}</textarea></div><div class="edit-field full"><label>Experience</label><textarea name="experience">{{ old('experience',$attorney->experience) }}</textarea></div><div class="edit-field full"><label>Experience Points <small>(one point per line)</small></label><textarea name="experience_points">{{ old('experience_points',$attorney->experience_points) }}</textarea></div><div class="edit-field"><label>Education <small>(one item per line)</small></label><textarea name="education">{{ old('education',$attorney->education) }}</textarea></div><div class="edit-field"><label>Admissions <small>(one item per line)</small></label><textarea name="admissions">{{ old('admissions',$attorney->admissions) }}</textarea></div>
</div><button class="edit-save" type="submit">Update attorney</button></form></div></main></body></html>
