<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\Capability; use Illuminate\Http\Request; use Illuminate\Support\Facades\File; use Illuminate\Support\Str;
class CapabilityController extends Controller {
 public function index(){return view('admin.capabilities', ['capabilities'=>Capability::latest()->get()]);}
 public function pages(){return view('admin.capability-pages', ['capabilities'=>Capability::orderBy('title')->get()]);}
 public function store(Request $request){$data=$request->validate(['title'=>['required','string','max:150'],'description'=>['required','string','max:1000'],'image'=>['nullable','image','mimes:jpg,jpeg,png,webp','max:5120']]);$data['slug']=Str::slug($data['title']);if($request->hasFile('image')){$data['image']=$this->storeImage($request,'image');}Capability::create($data);return back()->with('success','Capability added successfully.');}
 public function edit(Capability $capability){return view('admin.capabilities-edit', compact('capability'));}
 public function cardEdit(Capability $capability){return view('admin.capability-card-edit', compact('capability'));}
 public function cardUpdate(Request $request, Capability $capability){$data=$request->validate(['title'=>['required','string','max:150'],'description'=>['required','string','max:1000'],'image'=>['nullable','image','mimes:jpg,jpeg,png,webp','max:5120']]);if($request->hasFile('image')){$data['image']=$this->storeImage($request,'image');}$capability->fill($data)->save();return redirect()->route('admin.capabilities.index')->with('success','Capability card updated successfully.');}
 public function update(Request $request, Capability $capability){$data=$request->validate(['page_title'=>['nullable','string','max:150'],'page_description'=>['nullable','string'],'slug'=>['required','alpha_dash','max:160','unique:capabilities,slug,'.$capability->id],'experience'=>['nullable','string'],'representative_matters'=>['nullable','string'],'overview_heading'=>['nullable','string','max:200'],'overview_paragraph_one'=>['nullable','string'],'overview_paragraph_two'=>['nullable','string'],'image'=>['nullable','image','mimes:jpg,jpeg,png,webp','max:5120'],'hero_image'=>['nullable','image','mimes:jpg,jpeg,png,webp','max:5120'],'overview_image_left'=>['nullable','image','mimes:jpg,jpeg,png,webp','max:5120'],'overview_image_right'=>['nullable','image','mimes:jpg,jpeg,png,webp','max:5120']]);if(isset($data['experience'])){$data['experience']=str_replace('\\n', "\n", $data['experience']);}foreach(['image','hero_image','overview_image_left','overview_image_right'] as $field){unset($data[$field]);if($request->hasFile($field)){$data[$field]=$this->storeImage($request,$field);}}$capability->fill($data)->save();$capability->attorneys()->sync($request->input('attorney_ids',[]));return redirect()->route('admin.capabilities.pages')->with('success','Capability page updated successfully.');}
 public function destroy(Capability $capability){$capability->delete();return back()->with('success','Capability deleted successfully.');}
 private function storeImage(Request $request,$field='image'){ $image=$request->file($field);$directory=public_path('uploads/capabilities');File::ensureDirectoryExists($directory);$file='capability-'.Str::uuid().'.'.$image->getClientOriginalExtension();$image->move($directory,$file);return 'uploads/capabilities/'.$file;}
}
